set(_AMENT_PACKAGE_NAME "temperature")
set(temperature_VERSION "0.0.0")
set(temperature_MAINTAINER "ros <ruiiwata837@gmail.com>")
set(temperature_BUILD_DEPENDS )
set(temperature_BUILDTOOL_DEPENDS "ament_cmake")
set(temperature_BUILD_EXPORT_DEPENDS )
set(temperature_BUILDTOOL_EXPORT_DEPENDS )
set(temperature_EXEC_DEPENDS )
set(temperature_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(temperature_GROUP_DEPENDS )
set(temperature_MEMBER_OF_GROUPS )
set(temperature_DEPRECATED "")
set(temperature_EXPORT_TAGS)
list(APPEND temperature_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
